# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
        curl --user ${{secrets.JFROG_API_USER}}:${{secrets.JFROG_API_KEY}} https://sntdrctopoc.jfrog.io/artifactory/almrepo/oracle-java/jdk-8u211-linux-x64.tar.gz --output ./jdk-8u211-linux-x64.tar.gz
        curl -X GET --user ${{secrets.JFROG_API_USER}}:${{secrets.JFROG_API_KEY}}  https://sntdrctopoc.jfrog.io/artifactory/maven-releases/limit-manager-microservice/limit-manager/1.9.0/limit-manager-1.9.0.jar --output ./limit-manager-1.9.0.jar
        curl --user ${{secrets.JFROG_API_USER}}:${{secrets.JFROG_API_KEY}}  https://sntdrctopoc.jfrog.io/artifactory/almrepo/sonar-scanner/sonar-scanner-cli-3.2.0.1227-linux.zip --output ./sonar-scanner-cli-1.zip
        curl --user ${{secrets.JFROG_API_USER}}:${{secrets.JFROG_API_KEY}}  https://sntdrctopoc.jfrog.io/artifactory/maven-releases/com/isb/ccsw/sgs/sgs-auth/4.0.1/sgs-auth-4.0.1.jar --output ./sgs-auth-4.0.1.jar
        curl --user ${{secrets.JFROG_API_USER}}:${{secrets.JFROG_API_KEY}}  https://sntdrctopoc.jfrog.io/artifactory/maven-releases/es/santander/adn360-security/1.1.5/adn360-security-1.1.5.jar --output ./adn360-security-1.1.5.jar
        

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install Jfrog
        uses: jfrog/setup-jfrog-cli@v1
      - name: Get Version
        run: |
          jfrog rt config sntdrctopoc --url=https://sntdrctopoc.jfrog.io/artifactory --user=${{secrets.JFROG_API_USER}} --password=${{secrets.JFROG_API_KEY}} --interactive=false
          jfrog rt mvn install --build-name=${{ github.repository }} --build-number=${{github.run_number}}
          jfrog rt u "*.jar" libs-snapshot --build-name=${{ github.repository }} --build-number=${{github.run_number}} --props "key1=${{secrets.JFROG_API_USER}};build-number=${{github.run_number}};key2=${{secrets.JFROG_API_KEY}}"
          jfrog rt bce ${{ github.repository }} ${{github.run_number}}
          jfrog rt bp ${{ github.repository }} ${{github.run_number}}
